### ISSUE TITLE
Funding of a ticket without FND's still updates the github ticket

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#1]
![image](https://user-images.githubusercontent.com/6882032/31052654-437308e4-a68b-11e7-9903-13f09af5219c.png)

**Comment by karelstriegel** [comment]
![image](https://user-images.githubusercontent.com/6882032/31052716-124532c2-a68d-11e7-8538-05e655f4a03b.png)

![image](https://user-images.githubusercontent.com/6882032/31052718-1c84b730-a68d-11e7-8f9f-22728d557b6a.png)

**Comment by fundrequest-notifier** [comment]
Great! Dimitris Baltas funded 30 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Fabian Culot funded 0 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by nicohaelterman** [comment]
It is not possible anymore to fund 0FND...so this issue is solved...and closed

<img width="1437" alt="screen shot 2017-12-19 at 23 30 44" src="https://user-images.githubusercontent.com/30970721/34181984-ba7f2176-e514-11e7-820a-57a930cbdd62.png">
