### ISSUE TITLE
Logout should clear user cache

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/platform#109]
### Expected behaviour
User cache is cleared after logging out

### Actual behaviour
User cache remains present, when user logs in, old data is retrieved

### Steps to reproduce the behaviour
- login / logout / login

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/20/badge)](http://localhost:8080/requests/20) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @davyvanroy for your code contribution. [The reward](http://localhost:8080/requests/20) linked to this issue has been transferred to your account.

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
