### ISSUE TITLE
Changing my (confirmed) ETH address gives a "Something Went Wrong"

### ISSUE THREAD

**Issue by berkes** [FundRequest/platform#116]
### Expected behaviour

The address is added and saved.

### Actual behaviour

The address is not saved and I get a "Something went wrong" in red underneath the text-input-field.

### Steps to reproduce the behaviour
- Have the Adddress set to the address used in the ICO
- Get a new wallet, copy the address from there.
- Attempt to change to that address.

**Comment by Qkyrie** [comment]
Hi @berkes , in what module does the problem occur? On the current alpha or the profile application?

**Comment by berkes** [comment]
I went back to make screenshots. But now cannot reproduce it anymore. It stores my ETH address just fine. No idea if something changed, though.

![fnd_eth_add](https://user-images.githubusercontent.com/77059/39307702-d1a3e9dc-4963-11e8-9939-37ce5e2d8f4e.png)

In any case :point_up_2: is where it happened.

Since it's fixed -for me-, should I close this issue?

**Comment by Qkyrie** [comment]
We migrated a lot of things, so it's quite possibly fixed already. We'll close it for now. If it's a problem that still exists, I'm sure it'll pop up sooner or later! :)

**Comment by karelstriegel** [comment]
@berkes  thx for taking the time to report the issue ! Much appreciated
