### ISSUE TITLE
Activity stream should from the start display the last 25 events

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#12]
- [ ] At the start the activity display is empty, it should display the last 25 events 
- [ ] when scrolling to the end it should load the next 25 events, and so on...

**Comment by nicohaelterman** [comment]
Activity stream is back on...see screenshot...issue closed

![screen shot 2017-12-04 at 22 21 58](https://user-images.githubusercontent.com/30970721/33576902-a27b4cd2-d941-11e7-9821-6ad0e2fb649b.png)
