### ISSUE TITLE
Add a decentralized Secure Identity provider to our authentication providers

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#13]
Add a decentralized Secure Identity provider to our authentication providers

**Comment by friedger** [comment]
blockstack maybe?

**Comment by karelstriegel** [comment]
@friedger thx for sharing we where checking out Civic (is already implemented in a feature branch) and uport

**Comment by karelstriegel** [comment]
/close

We've opted to drop Civic as primary authentication provider, and went back to GitHub + Google. 
We plan to add Civic support in a later stage directly in the user profile.
