### ISSUE TITLE
setup DLQ for all queues

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/platform#133]
-

**Comment by Qkyrie** [comment]
Setting up declarative DLQs in the JmsConfig.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/6/badge)](https://dev-web.fundrequest.io/requests/6) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Qkyrie for your code contribution. The reward linked to this issue has been transferred to your account.

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/6/badge)](http://localhost:8080/requests/6) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Qkyrie for your code contribution. The reward linked to this issue has been transferred to your account.

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
