### ISSUE TITLE
Claimable request badge not displayed with correct colors

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/platform#144]
### Expected behavior
nice looking badge for all statuses for requests

### Actual behavior
not nice looking badge
<img width="311" alt="afbeelding" src="https://user-images.githubusercontent.com/668625/39485220-65650616-4d78-11e8-8fb0-315307b9f837.png">

### Steps to reproduce the behavior
go to a claimable request

**Comment by Simsteve7** [comment]
@karelstriegel , I added some random colors to the badges. Can you add the correct color codes and type of badges in this ticket?
