### ISSUE TITLE
Display version in the frontend of the platform

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#15]
### Expected behavior
For each build/deploy the frontend should display the version of the code

Could be added after or before the copyright 
![image](https://user-images.githubusercontent.com/6882032/31128195-555d36a2-a851-11e7-8347-9c71d688ab31.png)

Idealy it would also act as a link to our github platform repository and if possible link it to either a tag or to a commit hash.

### Actual behavior
Currently the version is not visisble

### Steps to reproduce the behavior
Just surf to the platform application

**Comment by nicohaelterman** [comment]
@Simsteve7 and @davyvanroy : 
now, the version is displayed like this: © 2018 - FundRequest - 0.1
Maybe, display like this: © 2018 - FundRequest - version 0.1

**Comment by Simsteve7** [comment]
Done
