### ISSUE TITLE
When a funding transaction fails I get an error message, but I cannot remove the error message

### ISSUE THREAD

**Issue by gerbert-vandenberghe** [FundRequest/platform#155]
### Expected behaviour

The error message should disappear automatically after some time and/or when I click the 'x' to make it disappear.

### Actual behaviour

The error message stays on the screen, also when clicking the 'x'.

### Steps to reproduce the behaviour

1. Make sure you have no eth and or fnd in your metamask wallet.
2. Fund a new issue.
3. Confirm the transactions in metamask.
4. The error message is displayed.

### Extra information

1. The message says to contact the FundRequest team. Also add a link to a contact page or email address or ...
2. The error is in Chrome.

**Comment by Qkyrie** [comment]
Issue was already solved by @Simsteve7 

Added a link to help.fundrequest.io
