### ISSUE TITLE
As a user I am able to star an issue and see it in my list of starred issues

### ISSUE THREAD

**Issue by gerbert-vandenberghe** [FundRequest/platform#161]
### Expected behaviour

In the overview and detail of issues I can (un)star an issue. The issues I star show up in my list of starred issues.

### Actual behaviour

It is not possible to star an issue.

**Comment by karelstriegel** [comment]
The star doesn't always appear, when it does the functionality works.
It doesn't matter if it is starred or not, both cases the start is sometimes not visible.
