### ISSUE TITLE
Before approving, I want a proper message of what the transaction will actually be doing

### ISSUE THREAD

**Issue by Qkyrie** [FundRequest/platform#168]
### Expected behaviour
I want a proper message to ask permission for approval

### Actual behaviour
random transaction gets requested

**Comment by fundrequest-notifier** [comment]
When pressing "send transaction" , before going to metamask, a popup should appear (like with the QR code) to explain there will be two transactions , one to approve the access the tokens and one which will perform the action transaction.

Please be aware that this popup should only appear when the approve has not been called yet , so normally one per address / per token.
