### ISSUE TITLE
Get QR-Code button for Trust-wallet doesn't work for the moment

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/platform#170]
### Expected behaviour
Get QR-code for Trust-wallet button worked before, but now when clicking the button nothing happens

### Actual behaviour
Get QR-Code button for Trust-wallet doesn't work for the moment

### Steps to reproduce the behaviour
see screenshot
<img width="1431" alt="screen shot 2018-05-03 at 21 58 52" src="https://user-images.githubusercontent.com/30970721/39599911-71fdeb4e-4f1d-11e8-9a49-7075378cd213.png">

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/20/badge)](https://dev-web.fundrequest.io/requests/20) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #170`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
