### ISSUE TITLE
Block the wizard step if the user doesn't have enough funds in his balance

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#201]
When web3 is selected and the funds are filling in, check if the user has enough funds in his account, if not, display a warning next to the funds + disable the button to go to the next step.

**Comment by karelstriegel** [comment]
Seems to have stopped working, reopen ticket

![image](https://user-images.githubusercontent.com/6882032/40083766-7bbeed0a-5895-11e8-8a87-5d648cc49a79.png)

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/28/badge)](https://dev-web.fundrequest.io/requests/28) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #201`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
