### ISSUE TITLE
"Funded by" missing "you" badge if applicable

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#204]
In the funded by tab of a request detail , if one of the funder is the logged in user, to "You" badge is missing. Please check sketch for more detail.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/35/badge)](https://dev-web.fundrequest.io/requests/35) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #35`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/35/badge)](https://dev-web.fundrequest.io/requests/35) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Simsteve7 for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/35).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
