### ISSUE TITLE
Using Google login, the name with non-ascii chars is not shown correctly

### ISSUE THREAD

**Issue by friedger** [FundRequest/platform#21]
### Expected behavior
Show my name correctly below the profile image

### Actual behavior
name is shown with ? chars instead of ü (and the like)

### Steps to reproduce the behavior
- add non-ascii chars to your name in your google profile
- login to fundrequest with google
- look at your profile in the top left corner

![bildschirmfoto vom 2017-10-12 12-04-09](https://user-images.githubusercontent.com/1449049/31490838-a1e2e06c-af45-11e7-8da9-80ca743c25f3.png)

**Comment by fundrequest-notifier** [comment]
Great! Karel Striegel funded 531 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Karel Striegel funded 13 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Karel Striegel funded 234 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Karel Striegel funded 124 FND to this issue. For more information, go to https://fundrequest.io.

**Comment by fundrequest-notifier** [comment]
Great! Karel Striegel funded 124 FND to this issue. For more information, go to https://fundrequest.io.
