### ISSUE TITLE
Default sorting of the overview should be New to old 

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#211]
* Default sorting of the personal overview should be New to old. That sorting option should also be added to the sort dropdown selections.

* Default sorting of the general overview should be old to new. That sorting option should also be added to the sort dropdown selections.

*  Default sorting of the pending overview in the "your request" should be from new to old instead of old to new

**Comment by Simsteve7** [comment]
@karelstriegel, sorting on 'latest created' or on 'latest funded' ?

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/48/badge)](https://dev-web.fundrequest.io/requests/48) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #48`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by karelstriegel** [comment]
**Not completed**
- [ ] Default sorting of the personal overview should be New to old.

**Comment by karelstriegel** [comment]
@nico-ptrs , is this following also resolved? (I'm adding this , to make sure I don't forget to test it)

bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1 TypeError: Cannot read property 'sort' of undefined
    at a.e.mounted (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at Ce (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at Object.insert (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at E (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at pn.__patch__ (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at pn.t._update (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at pn.<anonymous> (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at je.get (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at new je (bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1)
    at bundle-cb08b9504a89d4e4a67852c7b2e37cc1.js:1

![image](https://user-images.githubusercontent.com/6882032/40143484-d5b8bcac-595b-11e8-85f4-ab1be983a28e.png)

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/48/badge)](https://dev-web.fundrequest.io/requests/48) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/48).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
