### ISSUE TITLE
Problems 06/11/2017

### ISSUE THREAD

**Issue by Qkyrie** [FundRequest/platform#25]
- [x] Unable to start a request
- [x] Search bar disappeared
- [x] logout doesn't work (still pointing to old auth mec.)
- [x] Logo looks messed up

**Comment by Qkyrie** [comment]
1) Can't add tags to a request
--> 
![image](https://user-images.githubusercontent.com/2153990/32451097-54451b10-c316-11e7-85bd-c5b71f40ec7f.png)

**Comment by Qkyrie** [comment]
2) Adding a new request adds an empty row instead of the request
![image](https://user-images.githubusercontent.com/2153990/32451185-8232907a-c316-11e7-88f2-b005bd29f332.png)

**Comment by nicohaelterman** [comment]
@Qkyrie: can you review this issue, and close it if all done?

**Comment by Qkyrie** [comment]
I will
