### ISSUE TITLE
When an issue is referenced in more than one issue/pull request, the system doesn't detect it's claimable

### ISSUE THREAD

**Issue by nico-ptrs** [FundRequest/platform#250]
### Prerequisites:
1. an issue is referenced in more than one issue/pull request (e.g. https://github.com/FundRequest/area51/issues/105)
2. a pull request is created for this issue and merged -> issue is closed

### Expected behaviour

When the solver goes to the issue in the appliciation, the "Claimable" button should show 

### Actual behaviour

When the solver now goes to the issue in the appliciation, the "Add Funds" button is shown

**Comment by karelstriegel** [comment]
Please also check out #265

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/46/badge)](https://dev-web.fundrequest.io/requests/46) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #46`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/46/badge)](http://localhost:8080/requests/46) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #250`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/46/badge)](https://dev-web.fundrequest.io/requests/46) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/46).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
