### ISSUE TITLE
Move fundrequest logo from the github comment to the first badge 

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#252]
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/aa88dd38-da57-4574-9d2f-42c9ec78dfdc)

The fundrequest logo on the right should be moved and scaled into the first badge before the text "funding"

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/45/badge)](https://dev-web.fundrequest.io/requests/45) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #45`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/45/badge)](https://dev-web.fundrequest.io/requests/45) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Simsteve7 for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/45).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
