### ISSUE TITLE
Bug in the solver detection

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#265]
If an issue is open and there is a merge request that is referenced and that has been merged, but the ticket is still open, and then funds are added you get the below output. 

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/4190db7e-897a-4a43-991d-c51546e76b78)

The 2nd comment should not exist, it should update the first comment. Plus it should only be claimable of the issue is closed.

**Comment by karelstriegel** [comment]
Linked to #250

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/57/badge)](https://dev-web.fundrequest.io/requests/57) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #265`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/57/badge)](https://dev-web.fundrequest.io/requests/57) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/57).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
