### ISSUE TITLE
Update modal text when funding for the first time

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#266]
Update text of extra screen when funding with a ERC20 token for the first time

### 3th bullet point

Current
>So when clicking 'Send transaction' you'll have submit 2 transactions. The first one is to approve the tokens, the 2nd one is to fund.

Should be
>So when clicking 'Send transaction' you'll be offered 2 transactions. The first one is for you to approve funding in ZRX tokens, the 2nd one is to transfer the ZRX tokens to the request.

### Update the button

Current
>Send transaction.

Should be
>Continue transaction.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/58/badge)](https://dev-web.fundrequest.io/requests/58) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #266`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/58/badge)](https://dev-web.fundrequest.io/requests/58) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @davyvanroy for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/58).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
