### ISSUE TITLE
'you' badge in funders display settings

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#267]
In the funded by you , you should see the 'you' badge not only behind your name but also behind the eth address if that address is the same as in your profile.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/43/badge)](https://dev-web.fundrequest.io/requests/43) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #43`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/43/badge)](https://dev-web.fundrequest.io/requests/43) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @davyvanroy for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/43).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
