### ISSUE TITLE
Default gas limit is too low when funding with trustwallet (eip67)

### ISSUE THREAD

**Issue by davy-vr** [FundRequest/platform#275]
### Expected behaviour
When funding using trustwallet, everything should go correct without manually having to alter settings (like gas limit)

### Actual behaviour
Default gas limit is too low, resulting in a failed transaction. User has to manually check this and increase the gas limit
![afbeelding.png](https://images.zenhubusercontent.com/5aabc8f34b5806bc2bcb2365/e7b7416b-b788-41a3-8aea-1f7dd4920c65)

### Steps to reproduce the behaviour
- Fund using trust wallet without changing gas limit

**Comment by karelstriegel** [comment]
Testing blocked by  https://github.com/FundRequest/platform/issues/379
