### ISSUE TITLE
Change the link behind "how does it work" on the home page

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#289]
Please update the link behind "how does it work" to "https://help.fundrequest.io/how-does-it-work" , should open in a new tab.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/52/badge)](https://dev-web.fundrequest.io/requests/52) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #52`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/52/badge)](https://dev-web.fundrequest.io/requests/52) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Simsteve7 for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/52).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
