### ISSUE TITLE
Admin Panel: Add a link to the fundrequest request (currently only github link)

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#292]
In claim lists of the admin panel, please add an extra column, a link to the fundrequest request (currently only github link)

**Comment by karelstriegel** [comment]
On staging the link points to localhost:

![image](https://user-images.githubusercontent.com/6882032/41718459-5507a6f4-755d-11e8-86da-d40a52240899.png)

**Comment by davyvanroy** [comment]
wrong property was used

**Comment by karelstriegel** [comment]
still wrong location

![image](https://user-images.githubusercontent.com/6882032/42446525-e9c5c38a-8376-11e8-89ea-c24ee98fe9a2.png)
