### ISSUE TITLE
Enable identity verification for intercom

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/platform#299]
For intercom, you can verify your users, please read:
https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-identity-verification-on-your-web-product

this should be enforced

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/63/badge)](https://dev-web.fundrequest.io/requests/63) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #299`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/63/badge)](https://dev-web.fundrequest.io/requests/63) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @davyvanroy for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/63).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
