### ISSUE TITLE
Add link to the manual in the landing-page of the Alpha

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#3]
Manual contains faucet-process, link to github to report issue's, link to slack, ...
Therefore, not to overload the MVP-welcome-page, only add a link to the MVP-manual

Apha home should link to the test docs

**Comment by nicohaelterman** [comment]
Link to manual is added...so, ticket can be closed

<img width="1436" alt="screen shot 2017-12-19 at 23 33 20" src="https://user-images.githubusercontent.com/30970721/34182042-08f4e994-e515-11e7-8768-444a88b50682.png">
