### ISSUE TITLE
The border at the end of the list is not wel shown (cosmetics) - technologies and Funded column at the end of the list

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/platform#30]
The border at the end of the list is not wel shown (cosmetics) - 
--> technologies and Funded column at the end of the list: border is not well shown

+ TYPO! summery column ==> summ**a**ry

<img width="1226" alt="screen shot 2017-11-07 at 23 51 43" src="https://user-images.githubusercontent.com/30970721/32522336-362d32d2-c417-11e7-9614-a3fe4c23dadd.png">

**Comment by nicohaelterman** [comment]
TYPO! summery column ==> summary

Not fixed yet

**Comment by Simsteve7** [comment]
[x] fix typo
[x] update border

**Comment by nicohaelterman** [comment]
Ok, all fixed, and ticket closed

![screen shot 2017-11-28 at 07 44 35](https://user-images.githubusercontent.com/30970721/33305847-1fd795be-d410-11e7-959e-da38b6829b2f.png)
