### ISSUE TITLE
When a pull request fixes multiple issues, requests can't be claimed anymore

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#301]
### Expected behaviour
When a pull request closes multiple issues, then the solver should be able to claim each request that is solved by the pull request. 

### Actual behaviour
Non of the requests that are linked to closed github issues are claimable. They are in the correct state, but the solver is not recognised 

### Steps to reproduce the behaviour
- Create two tickets
- fund at last one of the tickets
- Create one pull request, that fixes both issues
- Try to claim the request(s)

**Comment by nico-ptrs** [comment]
Tried to reproduce this using https://github.com/FundRequest/area51/issues/122 and https://github.com/FundRequest/area51/issues/123 and it works. I think it is already fixed by https://github.com/FundRequest/platform/issues/265
