### ISSUE TITLE
Request 1 gives 404, while it is visible in the request list

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#303]
Request nr 1 is visible in the request overview, but when going to the detail page we get a 404, https://dev-web.fundrequest.io/requests/1

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/49/badge)](https://dev-web.fundrequest.io/requests/49) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #49`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by Qkyrie** [comment]
Will be fixed after @davyvanroy has correctly migrated the new keycloak

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/49/badge)](https://dev-web.fundrequest.io/requests/49) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @karelstriegel for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/49).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
