### ISSUE TITLE
Request comments - Last modified - Request detail/overview links

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#312]
- [x] Hide/Remove the request type icon foreach request in both request overviews
 ![image](https://user-images.githubusercontent.com/6882032/40113359-7d63fc58-5909-11e8-8434-ba77a073c864.png)

- [x] Add a link to the GitHub icon  foreach request in both request overviews, to the correct github issue.
![image](https://user-images.githubusercontent.com/6882032/40113461-ce8e4020-5909-11e8-8f2c-79152e691dd6.png)

- [x] Add a link to the Comments icon  foreach request in both request overviews, to the correct request details / comments tab
![image](https://user-images.githubusercontent.com/6882032/40113487-e5aca8f0-5909-11e8-8ab6-7a9a937240b6.png)

- [x] Show time indicate of the 'last modified date' next to the small icon on each request in the request overviews. Please indicate the last modified date as e.g "Few minutes ago, Few days ago, couple of weeks, couple of months ago..")

- [x] Add the comments tab in the request detail + load the comments from the github issue.
![image](https://user-images.githubusercontent.com/6882032/40113527-0b7fa87a-590a-11e8-98fe-23d208f63d58.png)

**Comment by karelstriegel** [comment]
Add a comment to test the comments

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/67/badge)](https://dev-web.fundrequest.io/requests/67) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #312`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/67/badge)](https://dev-web.fundrequest.io/requests/67) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/67).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
