### ISSUE TITLE
On profile it is not clear to users if they are eligible for the github or stackoverflow reward if their account is created in 2018

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#319]
If you connect any github or stackoverflow account , this is what a users sees
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/e16e451f-2a43-436c-9226-4d2280e1d6f4)

If his account is created in 2018 he doesn't have the right to any rewards, but that is not clear in the current design. 

Please implement the design below for case where your account is to recent.
![image](https://user-images.githubusercontent.com/6882032/40127325-67e6508a-592f-11e8-88af-960e05813b30.png)

**Comment by Qkyrie** [comment]
![image](https://user-images.githubusercontent.com/2153990/40235202-cb6505b8-5aa9-11e8-90c1-e7bcee320552.png)
