### ISSUE TITLE
Status change claim approved to claimed sets the balance of the request to 0

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#320]
Request is approved, balance is correct.
status changed to claimed -> request balance is set to 0
Balance is 0 not only in the request detail, but also in the request overviews

issue : https://dev-web.fundrequest.io/requests/49
Tokens are transferred to the solver : https://kovan.etherscan.io/tx/0x20b86950289181e3a8a1d8ee13576aaa5cf939acaa5861763c76b2a0a37c6586

**Comment by Qkyrie** [comment]
Can this be reproduced? I think the only way this can happen is when when you refresh the page the exact moment that the claim has gone through.
