### ISSUE TITLE
When status is claimable but the github issue is reopend the request become unclaimable

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#325]
## Current behaviour
The normal flow is followed until a request becomes claimable. Then the github issue is reopend. At that this the request has the status claimable, but the claim btn doesn't appear. Making the request unclaimable. 
If the GitHub issue is closed again, then the claim btn appears again. 
Look at : https://dev-web.fundrequest.io/requests/57

## Preferred behaviour
If the issue is reopened when the request is  claimable, we should deactivate the claim butten and have a tooltip saying "GitHub issue needs to be closed in order to claim the reward."

That way if the issue is really resolved, the solver is able to claim. If the solution is incomplete he can make a 2nd pull request to complete the solution , and then claim the request. Or a 3th party provides a pull request which is merged , and solves the ticket. 

In the last case we are in the situation that 2 different pull request solve an issue flow

**Comment by karelstriegel** [comment]
@davyvanroy please review

**Comment by davyvanroy** [comment]
If it is reopened you could argue that it could be possible again to add funds  (and following the normal flow).

P.S.
Once the issue is claimed (and it would be reopend after that), it needs to keep the status claimed since it won't be possible to add funds / claim on the smartcontracts
