### ISSUE TITLE
Back to Application link gives an error page

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/platform#329]
### Expected behaviour
Back to the application

### Steps to reproduce the behaviour
Logged in for the first time
Added email
Confirmed the email verification

After refresh, got this page
<img width="1434" alt="screen shot 2018-05-17 at 12 16 27" src="https://user-images.githubusercontent.com/30970721/40171692-4dff1772-59cc-11e8-98ce-964af88a25f6.png">

When clicking "Back to Application", got this error screen
<img width="1430" alt="screen shot 2018-05-17 at 12 16 34" src="https://user-images.githubusercontent.com/30970721/40171708-5ae5bfea-59cc-11e8-81ed-9af5224fe920.png">

**Comment by karelstriegel** [comment]
Cannot reproduce. Currently fixed
