### ISSUE TITLE
As a funder I want to be able to ask for a refund 

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#342]
### Expected behaviour
When an issue is funded and for some reason is not getting resolved, the funders funds would be "lost". A funder should have the opportunity to request a refund. In the first version a manual approval is required to refund the funder. 

The initial goal of this request is to avoid locked funding.

**Comment by karelstriegel** [comment]
related issue : https://github.com/FundRequest/platform/issues/343

**Comment by karelstriegel** [comment]
Deployed the PR , but on TST1 I was unable to test the refund, was unable to find anything related to refunding...bit strange


![image](https://user-images.githubusercontent.com/6882032/42448787-ac313150-837e-11e8-9021-470169f6f9b9.png)

**Comment by nico-ptrs** [comment]
Above issues should be fixed, but I labeled this issue as blocked because certain refund-transaction fails (https://github.com/FundRequest/contracts/issues/57)
