### ISSUE TITLE
Pending requests do not appear anymore

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#348]
Pending requests do not show anymore in the "your request" overview

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/69/badge)](https://dev-web.fundrequest.io/requests/69) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #348`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/6/badge)](https://dev-web.fundrequest.io/requests/6) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. You can now claim [the reward](https://dev-web.fundrequest.io/requests/6) that is linked to this issue. This can be done directly from the [funded request](https://dev-web.fundrequest.io/requests/6).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
