### ISSUE TITLE
It looks as if it's possible to fund 0 FND, although the contract will fail

### ISSUE THREAD

**Issue by Qkyrie** [FundRequest/platform#351]
### Expected behaviour

It should not be possible to fund 0 FND/any token

### Actual behaviour

It looks possible

### Steps to reproduce the behaviour
- fund 0 FND

**Comment by karelstriegel** [comment]
should also be blocked in the wizard

**Comment by nico-ptrs** [comment]
It wasn't deployed to dev-web yet, now it is. But this issue should be tested on staging (=release version)
