### ISSUE TITLE
When a request is in state claim approved or approved, funding should not be possible anymore

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#353]
On the request detail , when the state is  approved or claimed, one still sees the "add funds" btn. The btn should be removed once a claim is approved.

**Comment by fundrequest-notifier** [comment]
[![](https://staging.fundrequest.io/requests/4/badge)](https://staging.fundrequest.io/requests/4) [![](https://staging.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #353`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://staging.fundrequest.io/requests/4/badge)](https://staging.fundrequest.io/requests/4) [![](https://staging.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. You can now claim the reward that is linked to this issue. This can be done directly from the [funded request](https://staging.fundrequest.io/requests/4).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
