### ISSUE TITLE
Cross check balance of total funding/tec/project

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#374]
### Steps to reproduce the behaviour
-

**Comment by fundrequest-notifier** [comment]
[![](https://staging.fundrequest.io/requests/3/badge)](https://staging.fundrequest.io/requests/3) [![](https://staging.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #374`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
