### ISSUE TITLE
Add a queue gateway between all communications with GitHub

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#383]
Add a queue gateway between all communications with GitHub
 - Adding GitHub comments
 - Retrieving GitHub emails

To goal is to be able to throttle the flow of messages in either direction and if a failure occurs the message is not lost but added back to the queue for later processing. 

In rare cases it can be a benefit of being able to pause the queue so we can put the comms towards GitHub on hold.

**Comment by Barisevren** [comment]
hi good project
