### ISSUE TITLE
Improve FAQ component

### ISSUE THREAD

**Issue by nico-ptrs** [FundRequest/platform#390]
Right now we duplicate a lot of code in both html and the controllers when putting the FAQ on a page. 

This should be made more reusable by creating a faq (vue)component that asynchronously fetches the faq-items from a rest-endpoint (by key).

**Comment by karelstriegel** [comment]
In staging, 
1. The subtitles are not shown
2. Faq is shown on profile and in the funding wizard, but not in the request overview and request detail page.

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/83/badge)](http://localhost:8080/requests/83) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](http://localhost:8080/requests/83). A developer can claim [the reward](http://localhost:8080/requests/83) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #390`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://tst1-web.fundrequest.io/requests/83/badge)](https://tst1-web.fundrequest.io/requests/83) [![](https://tst1-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @nico-ptrs for your code contribution. [The reward](https://tst1-web.fundrequest.io/requests/83) linked to this issue has been transferred to your account.

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
