### ISSUE TITLE
New referrals are not counted anymore

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/platform#394]
### Expected behaviour
Referral program works as expected

### Actual behaviour
No new referrals are being added

### Steps to reproduce the behaviour
- Refer a friend
- let friend signup

**Comment by karelstriegel** [comment]
They are still not added

**Comment by karelstriegel** [comment]
Referral doesn't work if a user signs up using an email address + password (meaning NOT using a social login)

![image](https://user-images.githubusercontent.com/6882032/41315221-27c3f672-6e8f-11e8-9371-c08a80d8a377.png)
