### ISSUE TITLE
Percentage is Unclear

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#4]
![image](https://user-images.githubusercontent.com/6882032/31122286-7809087c-a83b-11e7-8cf9-0c220abf5019.png)

**Comment by nicohaelterman** [comment]
There is no percentage anymore...and in the previous alpha version, this was also solved...so, issue can be closed

<img width="1436" alt="screen shot 2017-12-19 at 23 33 20" src="https://user-images.githubusercontent.com/30970721/34182108-358d1c9c-e515-11e7-82b6-e4eb02732717.png">
