### ISSUE TITLE
Create a deploy guide so developers can run the fundrequest platform locally. 

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#401]
Create a deploy guide so developers can run the fundrequest platform locally.

**Comment by ccallergard** [comment]
Yes please - I tried and failed. :sweat_smile:

**Comment by karelstriegel** [comment]
Drafting as we speak ^^

btw are you a windows or a linux/mac user ;-) ?

**Comment by karelstriegel** [comment]
@ccallergard if you want you can already test it , the guide + needed code changes are currently stored in the following branch : https://github.com/FundRequest/platform/tree/improve-local-setup

(be aware that you need to code from that branch in order to test the setup, since it is not yet merged to develop)

**Comment by ccallergard** [comment]
@karelstriegel Thanks, i'm on Linux.

**Comment by karelstriegel** [comment]
@ccallergard ah you are the real deal :-) 

In the meantime we've merged the guide to the develop branch.
