### ISSUE TITLE
Wrong solver is determined by solverresolver

### ISSUE THREAD

**Issue by davyvanroy** [FundRequest/platform#408]
### Expected behaviour
pauliax as solver

### Actual behaviour
karel striegel

### Steps to reproduce the behaviour
- https://fundrequest.io/requests/17
- https://github.com/FundRequest/contracts/issues/48

**Comment by karelstriegel** [comment]
Does not appear to be resolved. 
This is the test issue that I use : https://github.com/FundRequest/platform/issues/414 
Even though Nico offered the pull request, I can still claim it since I made the reference ...
