### ISSUE TITLE
Issues running locally

### ISSUE THREAD

**Issue by ccallergard** [FundRequest/platform#412]
### Expected behaviour
Following the README to successfully run a local development platform.

### Actual behaviour
File `tweb/src/main/resources/application-credentials.properties.template` mentioned in the README is missing.
Making my own file `application-credentials.properties` and filling the properties mentioned is not enough - Maven build fails.

### Steps to reproduce the behaviour
Follow current README.

**Comment by davyvanroy** [comment]
We have updated the readme and added the template. 
Can you try again following the readme to set it up?

If you encounter an issue while starting up, please share the contents from your terminal.

thx

**Comment by ccallergard** [comment]
Ok, building succeeds, not sure what was wrong with that earlier.
And platform runs :+1: 

But one thing I forgot earlier, when starting the dependencies:
In the beginning it warns that `AZRAEL_SIGN_ACCOUNT` and `AZRAEL_EXECUTE_ACCOUNT` are not set, and later crashes:

> azrael_1       | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'claimExecutorHealthIndicator' defined in URL [jar:file:/app.jar!/BOOT-INF/classes!/io/fundrequest/azrael/worker/health/ClaimExecutorHealthIndicator.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.fundrequest.azrael.worker.health.ClaimExecutorHealthIndicator]: Constructor threw exception; nested exception is java.lang.NumberFormatException: Zero length BigInteger

I set them to `2` and `3`, and then it works. Well, so far - I haven't tried anything yet.

**Comment by ccallergard** [comment]
Well, it worked once.
Now azrael startup fails like this:

> azrael_1       | Caused by: rx.exceptions.OnErrorNotImplementedException: Invalid response received: okhttp3.internal.http.RealResponseBody@1f3165e7
...
azrael_1       | 	at io.fundrequest.azrael.worker.events.listener.FundRequestPlatformEventListener.subscribeToHistoric(FundRequestPlatformEventListener.java:93) ~[classes!/:na]
azrael_1       | 	at io.fundrequest.azrael.worker.events.listener.FundRequestPlatformEventListener.importHistoric(FundRequestPlatformEventListener.java:63) ~[classes!/:na]
...
azrael_1       | [dd-agent-writer] WARN datadog.trace.agent.common.writer.DDApi - Error while sending 1 of 1 traces to the DD agent. java.net.ConnectException: Connection refused (Connection refused) (going silent for 5 minutes)

**Comment by ccallergard** [comment]
Today it works, seemingly randomly. I'm able to rebuild and restart with no problem.
Guess I'll close the issue if it stays working a while.

**Comment by davyvanroy** [comment]
Ok, I created a pull request for the missing variables that were not set for Azrael (updated the readme).

Good to hear it is working now, don't hesitate to contact us if you have any other issues 👍
