### ISSUE TITLE
Request value doesn't get updated when request is created, value is 0 but in the request detail is shows 200 FND

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#413]
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/d21e50d4-b9eb-4d27-a415-91e9b3b6a475)

To reproduce just fund a new issue

**Comment by karelstriegel** [comment]
Was able to reproduce see : https://github.com/FundRequest/platform/issues/442
will close this one

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/82/badge)](http://localhost:8080/requests/82) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](http://localhost:8080/requests/82). A developer can claim [the reward](http://localhost:8080/requests/82) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #413`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
