### ISSUE TITLE
Send email to claimer when Claim is approved.

### ISSUE THREAD

**Issue by Simsteve7** [FundRequest/platform#423]
### Expected behaviour

When my claim, as a resolver of a requests, is approved I receive an email with this message and transaction link.

### Actual behaviour

When my claim, as a resolver of a requests, is approved I don't get an email.

### Steps to reproduce the behaviour

* Solver: Solve an issue and claim the bounty
* Admin: Approve claim

**Comment by davyvanroy** [comment]
Should be implemented while listening on a "Claimed" event or something like that

**Comment by nico-ptrs** [comment]
Closing this -> it is a duplicate of https://github.com/fundrequest/platform/issues/487
