### ISSUE TITLE
Keyclock, missing template

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#425]
When a user signs up using username and password, he then needs to confirm using a email sign up link. Once he does, he gets a screen to take him back to the application

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/213d9f44-cf18-4a94-a8f8-e8182f9acc7c)

when he clicks on the link "back to application" he gets redirected to keycloak, but that page isn't yet styled in the fundrequest theme:

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/37fbabb3-4a4a-4b19-9550-b3b6feab6d97)

**Comment by Simsteve7** [comment]
Tested on prod and staging. Not reproducible (probably already solved with changes to the keycloak settings)
