### ISSUE TITLE
Staging keycloak f**** up

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#445]
Seems to be related to bringing down dev-web

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/ca301581-0993-4af3-9844-2963b9cc3bcc)

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/aee3d590-8ac1-4055-86d0-9f184a9131f1)

**Comment by davyvanroy** [comment]
dev-web url was not available
