### ISSUE TITLE
Chrome extention : Change the design of the info message to the same style of our wizard info messages

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#450]
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/2a2be700-b869-46d6-8a60-fd9ffd3501c7)

![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/49fdad2c-650b-4abf-b0e1-c39ec975a6b9)

**Comment by fundrequest-notifier** [comment]
[![](http://localhost:8080/requests/86/badge)](http://localhost:8080/requests/86) [![](http://localhost:8080/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](http://localhost:8080/requests/86). A developer can claim [the reward](http://localhost:8080/requests/86) by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #450`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by fundrequest-notifier** [comment]
[![](https://tst1-web.fundrequest.io/requests/86/badge)](https://tst1-web.fundrequest.io/requests/86) [![](https://tst1-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Simsteve7 for your code contribution. You can now claim [the reward](https://tst1-web.fundrequest.io/requests/86) that is linked to this issue. This can be done directly from the [funded request](https://tst1-web.fundrequest.io/requests/86).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
