### ISSUE TITLE
Chrome extention : As a user I would like to see if a claim for an issue has been requested

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#456]
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/249a7cbb-3a92-4e92-9323-c14047296e54)

If a request has the status "claim requested", it should be made visible on the GitHub issue.

**Comment by Simsteve7** [comment]
@nico-ptrs , @davyvanroy , is there a status like "claim requested" ?

**Comment by nico-ptrs** [comment]
@Simsteve7 yes there is: `CLAIM_REQUESTED`
