### ISSUE TITLE
When a request has no funds attached (due to a refund) the request should not be visible in the overal overview

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#494]
When a request has no funds attached (due to a refund) the request should not be visible in the overal overview.

But it should remain in personal overview.

**Comment by karelstriegel** [comment]
To be tested on the refund branch

**Comment by karelstriegel** [comment]
It is not visible in the overall overview, which is good, but it is also gone in the personal overview, there it should be visible in the "all" filter

**Comment by nico-ptrs** [comment]
Test on feature-342-ask-refund (PR #448)
