### ISSUE TITLE
Sorting of the FundRequest-issue list

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#5]
Default sorting should be on creation date

**Comment by Simsteve7** [comment]
@davyvanroy Can you add the creation date to the requestDto?

**Comment by nicohaelterman** [comment]
Default sorting seems to be on the FundRequestIssue-url...so, last create Area51 issue is shown last.

see last created issue with url = https://alpha.fundrequest.io/#/requests/20 as the last element of the list

So, issue can be closed

<img width="1440" alt="screen shot 2017-12-19 at 23 36 58" src="https://user-images.githubusercontent.com/30970721/34182200-8acddb88-e515-11e7-8174-bb434179b223.png">
