### ISSUE TITLE
Tab navigation is broken due to refactor uri/get parameters

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#501]
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/930ecb27-fe68-479a-b6db-ec3de22325b3)

#comments -> should make the tab comments active, but we remain in the info tab of a request detail. 

Cause by this feature : https://github.com/FundRequest/platform/issues/432

**Comment by nico-ptrs** [comment]
This issue is obsolete since the comments are no longer displayed in a separate tab (they are now displayed under the description). 
The details tab seems to be working fine.
