### ISSUE TITLE
When trying to fund more then approved on the balance, additional approval doesn't work correctly

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/platform#51]
Testcase: add more funds than approved

User feedback is that an additional amount has to be approved...but this seems not to be working correctly

### Steps to reproduce the behavior
![screen shot 2017-12-04 at 22 58 16](https://user-images.githubusercontent.com/30970721/33578378-a925d2d2-d946-11e7-82d3-331c90075d56.png)

![screen shot 2017-12-04 at 22 57 08](https://user-images.githubusercontent.com/30970721/33578382-a9a9dcda-d946-11e7-83fa-c021134b39b2.png)

![screen shot 2017-12-04 at 22 57 48](https://user-images.githubusercontent.com/30970721/33578381-a97ebfaa-d946-11e7-8a51-122bbd5ee9d4.png)

![screen shot 2017-12-04 at 22 57 57](https://user-images.githubusercontent.com/30970721/33578379-a9533272-d946-11e7-8094-4faf61417ff9.png)

![screen shot 2017-12-04 at 22 59 45](https://user-images.githubusercontent.com/30970721/33578445-d9ccb55e-d946-11e7-9c20-f5c72a111b64.png)

**Comment by Simsteve7** [comment]
@nicohaelterman In metamask, the transactions are still blue, so they aren't executed yet. We have to check if it's a bug in metamask or in angular.

**Comment by Simsteve7** [comment]
@nicohaelterman I noticed if I add a default gasprice (for example: 300.000) then metamask doesn't do anything if you push the 'submit' button. I'll put it to a gasprice that is to low, so the user has to change it before pushing submit. Then metamask works correctly.

**Comment by nicohaelterman** [comment]
Re-tested, and ok.

https://alpha.fundrequest.io/#/requests/1 was funded for 30FND. 
Approval balance was 10. 
Additional funding of 20.
User get feedback that only 10 is approved, and an additional 10 will be added to the balance and be used for the additional funding.
End-result: https://alpha.fundrequest.io/#/requests/1 was funded for 50 FND
Re-test OK

<img width="1427" alt="screen shot 2017-12-19 at 23 01 22" src="https://user-images.githubusercontent.com/30970721/34180899-9012554c-e510-11e7-9ab8-fcde286f7aa9.png">
