### ISSUE TITLE
Migrate  TST1 contract to new version to test the refund feature

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#510]
Issues funded as test : 
https://github.com/FundRequest/area51/issues/192
https://github.com/FundRequest/area51/issues/193
https://github.com/FundRequest/area51/issues/194

related FR requests:
https://tst1.fundrequest.io/requests/97
https://tst1.fundrequest.io/requests/98
https://tst1.fundrequest.io/requests/99

**Comment by Qkyrie** [comment]
Migration is done, newest FundRequestContract for Test environment = 0x55356bccfa48d09dc824c0aea6ebd868ff5edf50
