### ISSUE TITLE
It is possible to approve 0 FND's (and this transaction consumes gas)

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/platform#52]
### Expected behavior
It should only be possible to approve strictly more than 0 FND's

Note: probably this is expected behaviour, but this is not clear to a new user...maybe the naming of the approved should be different...something as "Wallet: approved saldo" (?)
And then the "approve"-modal view, can also be changed into "update wallet's approved saldo"

**TODO1:**
label "Approved for use: 0.00 FND" --> "Approved saldo"
button label "Approve FND's" --> "Update saldo"

**TODO2:**
titel of model dialog: "Approve FND's" --> "Update saldo"
label in model dialog: "Approve Amount" --> "Update approved saldo to:"

### Actual behavior
It is possible to approve 0 FND's --> this consumes gas :(

### Steps to reproduce the behavior
See screenshots

![screen shot 2017-12-04 at 23 09 16](https://user-images.githubusercontent.com/30970721/33578899-4c5b368a-d948-11e7-96f8-69bc64982765.png)

![screen shot 2017-12-04 at 23 09 26](https://user-images.githubusercontent.com/30970721/33578898-4c3ed2ec-d948-11e7-8ee4-64a831babfb7.png)

![screen shot 2017-12-04 at 23 09 36](https://user-images.githubusercontent.com/30970721/33578897-4c17439e-d948-11e7-8c72-7bcd52b35b60.png)

![screen shot 2017-12-04 at 23 10 40](https://user-images.githubusercontent.com/30970721/33578955-6f3cb674-d948-11e7-9c58-82476508fc86.png)

**Comment by nicohaelterman** [comment]
To be checked with @gerbert-vandenberghe

**Comment by davyvanroy** [comment]
This is actually desired behaviour, this is a way to 'reset' your approval.

The UI should be improved to allow the user to 'reset' his approval and only allow to approve >0 tokens (so split it up in 2 actions)

**Comment by Simsteve7** [comment]
Approve isn't necessary anymore. Done in 1 call.
