### ISSUE TITLE
As a Funder I want choose how long the mining of a funded issue should take

### ISSUE THREAD

**Issue by timdierckxsens** [FundRequest/platform#520]
### Problem
- By default the gwei in metamask is set to 1 Gwei
- 1 gwei is too low a fee and the issue remains pending for hours before it is funded

### Solution
- Give the funder a choice how long it should take. For example slow - med - fast
- Add the relative cost 

### Precondition
- The funder has selected an issue to fund
- The funder is on the payment overview, chooses to fund with metamask

### Scope
- The funder should be able to indicate how fast the funding proces should take
- The funder should see an indicative cost of how much fees (s)he will pay in gas fee

### Postcondition
- Metamask should prefill the correct amount
- The funder succesfully funded an issue

### Acceptance criteria
- Slider or other option
- indicative gas price that will be paid
- Can be on payment detail page or payment summary?

### Screenshots
![example mockup](https://user-images.githubusercontent.com/18101724/43582887-1fb76fe4-965e-11e8-8c2f-29d26a1c2d1f.png)

**Comment by davyvanroy** [comment]
For now, we can use this endpint for checking the gasprice: https://www.etherchain.org/api/gasPriceOracle

this would mean you need a "slider" with 4 possibilities. I would add the indication of max transaction price in $
