### ISSUE TITLE
As a user, I get notifications during the Funding process

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/platform#54]
Notification1 "You must be logged in to do this action": N/A for the Funding process...funding is only possible when logged in
![screen shot 2017-12-18 at 22 47 28](https://user-images.githubusercontent.com/30970721/34129729-7858c2d6-e445-11e7-880e-07c82cf1f269.png)

Notification2 "Transaction 'fund request' sent...Go to transaction" ==> renaming notification...more user-friendly notification like "Transaction submitted...Go to transaction"
![screen shot 2017-12-18 at 22 01 46](https://user-images.githubusercontent.com/30970721/34127915-1f26a134-e43f-11e7-8fc1-5dba1e68a6af.png)

Notification3 "Transaction is being processed" ==> this could also be Notification2 (tbd)

Notification4 "Transaction is processed" ==> in our first alpha, there was the message to the user that the transaction was registered in the blockchain...so, now there could be a notification to the user that the "Transaction is being processed"

**Comment by davyvanroy** [comment]
Has to be taken into account during design of new screens @karelstriegel
