### ISSUE TITLE
Transfer not working on mobile

### ISSUE THREAD

**Issue by gerbert-vandenberghe** [FundRequest/platform#552]
### Expected behaviour

When I click on 'send funds' I should get a pop up.

### Actual behaviour

The pop up is not displayed

### Steps to reproduce the behaviour

- Open Brave on iPhone. 
- Try to send funds.

**Comment by karelstriegel** [comment]
Issue moved to [FundRequest/ArkanePrivate #439](https://github.com/FundRequest/ArkanePrivate/issues/439) via [**ZenHub**](https://www.zenhub.com/)
