### ISSUE TITLE
As a user I only approve FND when I add funding to a specific issue.

### ISSUE THREAD

**Issue by nicohaelterman** [FundRequest/platform#57]
#### Context

Corrently a user can approve FND that becomes available to fund issues. When he has done so he can use this approved FND to put funding on issues.

Since this flow is not clear for the end user we will remove the option to approve FND as a separate action. In stead we will approve the FND in the funding flow, so that when a user add funding to an issue 2 transactions are sent to Metamask: the approve transaction and the transfer transaction.

#### Flow of events

1.

**Comment by Simsteve7** [comment]
Not relevant anymore
