### ISSUE TITLE
Unable to link Google and Github account to one keycloack account

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#58]
### Expected behaviour
Be able to have the option if you want to use the same account or a create a new account when logging into our platform via different social platforms (github/google) and both or using the same email. 

### Actual behaviour
![image](https://user-images.githubusercontent.com/6882032/34248420-4a00bc84-e636-11e7-9f1a-8906d56675f6.png)
![photo5902156733067930743](https://user-images.githubusercontent.com/668625/34301313-5de986bc-e72c-11e7-82d4-e643adb922a2.jpg)

### Steps to reproduce the behaviour
- Login with your github account
- Logout 
- Login with your google account , which uses the same email as your github account

**Comment by davyvanroy** [comment]
With the default keycloak theme, a form will be presented allowing you to insert additional details. Probably too much has been removed in this theme.

**Comment by gerbert-vandenberghe** [comment]
Hoi @Simsteve7 

zou je deze met prio willen opnemen?
