### ISSUE TITLE
fundrequest-notifier, not correctly showing decimal funds

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#6]
Funded 8.75 FND, notifier shows only 8

![image](https://user-images.githubusercontent.com/6882032/31122465-45dd201c-a83c-11e7-8e7b-24247d0f6876.png)

![image](https://user-images.githubusercontent.com/6882032/31122453-3834b402-a83c-11e7-936d-1777609c338f.png)

**Comment by nicohaelterman** [comment]
Initial state: https://alpha.fundrequest.io/#/requests/1 - 50FND
Funded 1,455
This is rounded to 1,46
When transaction processed, this is correctly shown as 51,46FND
Test OK

<img width="1425" alt="screen shot 2017-12-19 at 23 41 12" src="https://user-images.githubusercontent.com/30970721/34182355-21002160-e516-11e7-91e1-1daffc159bec.png">
