### ISSUE TITLE
As a user I don't see the CSS loading properly after registering on the platform

### ISSUE THREAD

**Issue by timdierckxsens** [FundRequest/platform#79]
### Expected behaviour
Nicely styled profile page

### Actual behaviour
fugly profile page

![screen shot 2018-03-12 at 12 23 51](https://user-images.githubusercontent.com/18101724/37281121-40c42940-25f0-11e8-8570-86d8d20f87d3.png)

### Steps to reproduce the behavior
- register using Gmail or Github
- verify your email address
- Look at the page

**Comment by davyvanroy** [comment]
closing for now
