### ISSUE TITLE
Update fundrequest link in github issue (point to detail page of a fundrequest request)

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#8]
Update fundrequest link to the detailed fundrequest issue page. (For example : https://alpha.fundrequest.io/requests/10)

![image](https://user-images.githubusercontent.com/6882032/31122561-a5c5c01a-a83c-11e7-9164-d31087e30ea7.png)

**Comment by nicohaelterman** [comment]
Merged into https://github.com/FundRequest/platform/issues/7
