### ISSUE TITLE
Dapp browser should be first choice 

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/platform#94]
### Expected behavior
Dapp browser should be the first choice

### Actual behavior
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/69c2a27e-bfa0-494a-940d-1adcdea42625)

### Steps to reproduce the behavior
Just fund an issue

**Comment by nicohaelterman** [comment]
<img width="1434" alt="screen shot 2018-05-03 at 21 52 48" src="https://user-images.githubusercontent.com/30970721/39599565-6d564d12-4f1c-11e8-806d-a7cb33bc16c4.png">
